### ISSUE TITLE
Cool Project, keep it up

### ISSUE THREAD

**Issue by Stuhl** [Nubb3r/PhoenixMod#1]
Halöle (Le rasierer hier),

Cooles Projekt. Denke mal du machst es alleine. Wusste nicht das es overhaul mods für das vanilla game gibt. Ist aufjedenfall nice zu sehen das einige sachen hier ausbalanciert werden die normalerweise broken sind wie z.b. wehr sniper upkeep cost usw.

Würde gerne contributen aber denke das es recht zeit aufwändig ist die ganzen dateien anzuschauen und zu entschlüsseln. Bin da actually auch 0 erfahren. Wünsche dir trotzdem viel Glück.

Hatte selber mal ne Idee gehabt ein richtiges replay System über das normale zu legen wie bei Starcraft 2 z.b. aber ist alles krank aufwändig weil man Daten aus dem game heraus lesen muss und hab da halt auch wieder 0 plan gerade weil es keine offene "API" dafür gibt.

**Comment by Nubb3r** [comment]
Was meinst du mit "richtigem replay system"?  Ich habe sc2 gespielt. Meinst du zurückspulbar?

**Comment by Stuhl** [comment]
Übersicht über alle Einheiten von beiden seiten, Einheiten getötet, Produzierte Einheiten etc.
So wie in Starcraft 2

Das geht aber leider nicht, die replay files speichern tatsächlich nur Aktionen des spielers und der rest wird dann ingame simuliert bzw. das Spiel mit den Aktionen gefüttert. Man müsste irgendwie die daten ingame mitloggen damit man irgendwas anstellen kann.
